### ISSUE TITLE
error ubuntu 16.04 can't get it to work 

### ISSUE THREAD

**Issue by korinth146** [baitisj/anki-voice-control#3]
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 41, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/q/Documents/Anki/addons/Voice Control.py", line 1, in <module>
    import voice_control.voice_control
  File "/home/q/Documents/Anki/addons/voice_control/voice_control.py", line 9, in <module>
    import pygst
ImportError: No module named pygst

**Comment by korinth146** [comment]
installed pygst but still doesn't work :(

**Comment by t-mak** [comment]
I have the same issue. 

Traceback (most recent call last):
  File "aqt/addons.py", line 41, in loadAddons
  File "/home/tom/.local/share/Anki2/addons/Voice Control.py", line 1, in <module>
    import voice_control.voice_control
  File "/home/tom/.local/share/Anki2/addons/voice_control/voice_control.py", line 9, in <module>
    import pygst
ImportError: No module named pygst

**Comment by multimeric** [comment]
This is somewhat answered here: https://github.com/baitisj/anki-voice-control/pull/1#commitcomment-21432104
